version: "3.8"
services:
  db:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: db
      POSTGRES_USER: ${DATABASE_USERNAME}
      PGUSER: ${DATABASE_USERNAME}
      PGDATABASE: db
      PGPASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 127.0.0.1:${DATABASE_LOCAL_PORT}:5432
    restart: always

  back:
    build: backend
    restart: always
    command: bash ./start_server.sh
    env_file:
      - .env
    environment:
      DATABASE_URI: ${PROD_DATABASE_URI}
    ports:
      - 127.0.0.1:${FORWARD_BACK_PORT}:80
    depends_on:
      - db

  front:
    build:
      context: frontend
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    volumes:
      - ./frontend/nginx/:/etc/nginx/conf.d/
    ports:
      - 127.0.0.1:${FORWARD_FRONT_PORT}:80

volumes:
  db_data:
