export const CHECK_TOKEN_LOGIN = "CHECK_TOKEN_LOGIN_LOGIN";
export const CHECK_TOKEN_CHANGE_PASSWORD = "CHECK_TOKEN_LOGIN_CHANGE_PASSWORD";
export const GET_ORDERS = "GET_ORDERS";
export const GET_USER_PRODUCTS = "GET_USER_PRODUCTS";
export const GET_USER_BUSINESS = "GET_USER_BUSINESS";
