"""added phone number for bussiness

Revision ID: 0419900c5420
Revises: ab75644d3c7f
Create Date: 2023-01-07 12:56:12.577577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0419900c5420"
down_revision = "ab75644d3c7f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "businesses", sa.Column("phone_number", sa.String(length=64), nullable=True)
    )
    op.execute("UPDATE businesses SET phone_number = 972545657514")
    op.alter_column("businesses", "phone_number", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("businesses", "phone_number")
    # ### end Alembic commands ###
