"""replace is_out_of_stoke to is_out_of_stock

Revision ID: 052b4302a1c0
Revises: c90fd8b91bb7
Create Date: 2022-12-25 17:38:47.474823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052b4302a1c0'
down_revision = 'c90fd8b91bb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_out_of_stock', sa.Boolean(), nullable=True))
    op.drop_column('products', 'is_out_of_stoke')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_out_of_stoke', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('products', 'is_out_of_stock')
    # ### end Alembic commands ###
