"""create models

Revision ID: 1088d32bd9e8
Revises: 
Create Date: 2022-11-10 23:35:21.486662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1088d32bd9e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=128), nullable=False),
    sa.Column('sms_confirmation_number', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('adress', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('orders_taken', sa.Integer(), nullable=True),
    sa.Column('items_sold', sa.Integer(), nullable=True),
    sa.Column('kg_sold', sa.Integer(), nullable=True),
    sa.Column('sms_used', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('Admin', 'Frozen', 'Marketeer', name='role'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=128), nullable=True),
    sa.Column('logo', sa.String(length=128), nullable=True),
    sa.Column('web_site_link', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'was_seen', 'completed', 'picked_up', 'cancelled', name='orderstatus'), nullable=True),
    sa.Column('customer_phone_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_phone_number'], ['customers.phone_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=128), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('sold_by', sa.Enum('by_kilogram', 'by_unit', name='soldby'), nullable=False),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.Column('is_display', sa.Boolean(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preps')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('businesses')
    op.drop_table('users')
    op.drop_table('customers')
    # ### end Alembic commands ###
