"""added sms_used

Revision ID: 2a6c6f66d04a
Revises: fc06b812430f
Create Date: 2023-01-11 16:38:50.859527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6c6f66d04a'
down_revision = 'fc06b812430f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('sms_used', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'sms_used')
    # ### end Alembic commands ###
