"""update order

Revision ID: 4f21279f4f50
Revises: 359db3fcdae0
Create Date: 2022-12-16 17:22:55.335393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f21279f4f50'
down_revision = '359db3fcdae0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('pick_up_data', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_deleted')
    op.drop_column('orders', 'pick_up_data')
    # ### end Alembic commands ###
