"""<message>

Revision ID: 606c5560c870
Revises: b6cd10f1b380
Create Date: 2022-12-05 14:14:35.534627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '606c5560c870'
down_revision = 'b6cd10f1b380'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=64), nullable=False),
    sa.Column('confirm_code', sa.String(length=6), nullable=True),
    sa.Column('is_number_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone_numbers')
    # ### end Alembic commands ###
