"""new db

Revision ID: 6b1a11237e2d
Revises: 606c5560c870
Create Date: 2022-12-06 15:46:59.113932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1a11237e2d'
down_revision = '606c5560c870'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone_numbers')
    op.add_column('customers', sa.Column('confirm_code', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'confirm_code')
    op.create_table('phone_numbers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('confirm_code', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('is_number_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='phone_numbers_pkey'),
    sa.UniqueConstraint('phone_number', name='phone_numbers_phone_number_key')
    )
    # ### end Alembic commands ###
