"""create PhoneNumber

Revision ID: 7df39c12dd38
Revises: 6b1a11237e2d
Create Date: 2022-12-07 17:19:15.579593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df39c12dd38'
down_revision = '6b1a11237e2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('confirm_code', sa.String(length=6), nullable=True),
    sa.Column('is_number_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.drop_table('customers')
    op.add_column('orders', sa.Column('phone_number_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('customer_name', sa.String(length=128), nullable=False))
    op.add_column('orders', sa.Column('note', sa.String(length=512), nullable=True))
    op.drop_constraint('orders_customer_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'phone_numbers', ['phone_number_id'], ['id'])
    op.drop_column('orders', 'customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_customer_id_fkey', 'orders', 'customers', ['customer_id'], ['id'])
    op.drop_column('orders', 'note')
    op.drop_column('orders', 'customer_name')
    op.drop_column('orders', 'phone_number_id')
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('is_number_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('confirm_code', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='customers_pkey'),
    sa.UniqueConstraint('phone_number', name='customers_phone_number_key')
    )
    op.drop_table('phone_numbers')
    # ### end Alembic commands ###
