"""added type user

Revision ID: ab75644d3c7f
Revises: 052b4302a1c0
Create Date: 2023-01-06 15:24:49.931948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab75644d3c7f'
down_revision = '052b4302a1c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_type', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    # ### end Alembic commands ###
