"""buisness

Revision ID: f7416d1e8b56
Revises: 9505a4b74788
Create Date: 2022-11-21 11:38:53.454350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7416d1e8b56'
down_revision = '9505a4b74788'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_uid', sa.String(length=36), nullable=True))
    op.add_column('preps', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('preps', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preps', 'is_active')
    op.drop_column('preps', 'is_deleted')
    op.drop_column('orders', 'order_uid')
    # ### end Alembic commands ###
